spring.application.name=mini-task
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mini-task-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ijse@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# JWT Configuration
jwt.secret=MyVerySecureSecretKeyForJWTTokenGenerationAndValidationPurposesOnly123456789
jwt.expiration=86400000

# Logging
logging.level.root=INFO
logging.level.com.example.mini_task=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Bootstrap Default Admin (first run)
app.bootstrap.admin.enabled=true
app.bootstrap.admin.first-name=Super
app.bootstrap.admin.last-name=Admin
app.bootstrap.admin.email=admin@gmail.com
app.bootstrap.admin.password=Admin@123
